package: redaxo_bootstrap
version: '0.0.1-dev'
author: Benjamin Hacker
supportpage: https://github.com/BenJ1337/redaxo_bootstrap

page:
  title: 'Redaxo Bootstrap'
  icon: rex-icon fa-link
  perm: admin

requires:
  php:
    version: '>=8.0.0'
  redaxo: '>=5.0.0'
  packages:
    redaxo_input_components: '>=0.0.1-dev'
